### Login ###
POST http://localhost:8000/api/v1/auth/login/
Content-Type: application/json

{
  "email": "admin@yopmail.com",
  "password": "dell@123"
}

### Refresh Token ###   
POST http://localhost:8000/api/v1/auth/token/refresh/
Content-Type: application/json

{
    "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTczOTM0MTMxMiwiaWF0IjoxNzM4MTMxNzEyLCJqdGkiOiIxNjk5NmI4ZmVmNWY0ZmQ2YWQwMmEwZTE4MWNlOGMxZiIsInVzZXJfaWQiOiJkMTE2NzA2Ny01MTJhLTQxM2EtODBjYi04MGQxMzk1NjIxZWIifQ.j7caM4ammGEDqsKckvOqslpbMnCppTDF64tpHYSKJ5M"
}

### Logout ###
POST http://localhost:8000/api/v1/auth/logout/
Content-Type: application/json

{
    "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTczOTM0MTUzMywiaWF0IjoxNzM4MTMxOTMzLCJqdGkiOiIzYjMxNGJkOTEzZjU0NTFhODJkNzY1ZDg4NzE3NzUyMSIsInVzZXJfaWQiOiJkMTE2NzA2Ny01MTJhLTQxM2EtODBjYi04MGQxMzk1NjIxZWIifQ.uG9U69ax7qzyLWzMTgn26mDcwk2cPbKh3O1gRaWuMDg"
}

### Change Password ###
POST http://localhost:8000/api/v1/auth/change-password/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM4NzM3OTQ4LCJpYXQiOjE3MzgxMzMxNDgsImp0aSI6IjBiNjdhNTI3MzdiYjRkNTg5N2E4NDU1ZWM4M2Y4YzkzIiwidXNlcl9pZCI6ImQxMTY3MDY3LTUxMmEtNDEzYS04MGNiLTgwZDEzOTU2MjFlYiJ9.-_4Reuk7lm5nq1rZoK82xdreaIGx1FQwEG15WbLL1No

{
    "current_password": "dell@123",
    "new_password": "Dell@1234",
    "confirm_password": "Dell@1234"
}

### Update User Profile ###
PUT http://localhost:8000/api/v1/auth/profile/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM4NzQyMTk5LCJpYXQiOjE3MzgxMzczOTksImp0aSI6ImMxNzkxNzlhMmY0MTQ4MTE5ZWY1MmI4ZDQyY2RhMjBhIiwidXNlcl9pZCI6IjE1MjNmYTQ0LWI0NDItNDYzMi04OWJmLWYxOWRmNWMxMjhjMSJ9.o25YDmCkz6S0YD6z-nQd_rxKYvoU69sxYytEAhP9USU

{
    "first_name": "John",
    "last_name": "Doe"
}

### Update User Profile (Partial) ###
PUT http://localhost:8000/api/v1/auth/profile/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM4NzQyMTk5LCJpYXQiOjE3MzgxMzczOTksImp0aSI6ImMxNzkxNzlhMmY0MTQ4MTE5ZWY1MmI4ZDQyY2RhMjBhIiwidXNlcl9pZCI6IjE1MjNmYTQ0LWI0NDItNDYzMi04OWJmLWYxOWRmNWMxMjhjMSJ9.o25YDmCkz6S0YD6z-nQd_rxKYvoU69sxYytEAhP9USU

{
    "first_name": "Johny"
}

### User Registration ###
POST http://localhost:8000/api/v1/auth/register/
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "Test@123",
  "confirm_password": "Test@123"
}

### User List - Admin Only ###
GET http://localhost:8000/api/v1/admin/users/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM4NzQ0NzI4LCJpYXQiOjE3MzgxMzk5MjgsImp0aSI6Ijk5YTkxYjc2NTU0MDRiZmNhOWNjMzUyYTYyMmI2Y2FkIiwidXNlcl9pZCI6ImQxMTY3MDY3LTUxMmEtNDEzYS04MGNiLTgwZDEzOTU2MjFlYiJ9.Y73eNCPJB8dLOMatL3XaRxLFwDxleGYvioz3_-KwLAY


### User Delete ###
DELETE http://localhost:8000/api/v1/auth/delete/2/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM4NzQ0NzI4LCJpYXQiOjE3MzgxMzk5MjgsImp0aSI6Ijk5YTkxYjc2NTU0MDRiZmNhOWNjMzUyYTYyMmI2Y2FkIiwidXNlcl9pZCI6ImQxMTY3MDY3LTUxMmEtNDEzYS04MGNiLTgwZDEzOTU2MjFlYiJ9.Y73eNCPJB8dLOMatL3XaRxLFwDxleGYvioz3_-KwLAY
